
//import { Component, ViewEncapsulation } from '@angular/core';

  enum language {
    language_english="English",
    language_hindi="हिंदी",
    language_marathi="मराठी",
  }
  enum language_english {
    downloadMsg="Content downloaded successfully.",
    updateMsg="Tap to Continue",
    interNetMsg="Please check your internet connectivity.",
    noUpdate="No Update Available.",
    Create_Your_Profile="Create Your Profile",
    Tap_to_here_to_create_your_profile="Tap here to create your Profile",
    User_Profile="User Profile",
    User_Name="Name",
    User_Type="User Type",
    Gender="Gender",
    Date_of_Birth="Date of Birth",
    Orgnization_Type="Organization Type",
    Preferd_Language="Preferred Language",
    Country="Country",
    State="State",
    District="District",
    Mobile_No="Mobile No.",
    Save="Save",
    Cancel="Cancel",
    overview="FP OVERVIEW",
    Faq="FAQ",
    keyMessage="KEY MESSAGE",
    counselling="COUNSELLING",
    Quiz="QUIZ",
    library="LIBRARY",
    incentive="SCHEME",
    AskUs="ASK US",
    Methods="CONTRACEPTIVE METHODS",
    submit="Submit",
    question_PlaceHolder="Write your feedback/query here...",
    questionError="Please enter your question",
    noDataFound="No Data Available.",
    correct="Correct",
    incorrect="Incorrect",
    response="The Correct Response is:-",
    incentiveLabel="Incentive ",
    indeminityLabel ="Indeminity ",
    levelText = "Level ",
    playQuiz= "Do You Want to Play Again?",
    quizAlert="Please complete both levels of the quiz first.",
    quizMessage="Please try again after 48 hours."
   }
  enum language_hindi {
    downloadMsg="सामग्री सफलतापूर्वक डाउनलोड की गई।",
    updateMsg="जारी रखने के लिए बटन दबाएं",
    interNetMsg="कृपया अपनी इंटरनेट कनेक्टिविटी की जाँच करें।",
    noUpdate="कोई अद्यतन उपलब्ध नहीं है।",
    Create_Your_Profile="अपना प्रोफ़ाइल बनाए",
    Tap_to_here_to_create_your_profile="अपनी प्रोफ़ाइल बनाने के लिए यहां टैप करें",
    User_Profile="उपयोगकर्ता प्रोफ़ाइल",
    User_Name="नाम",
    User_Type="उपयोगकर्ता का प्रकार",
    Gender="लिंग",
    Date_of_Birth="जन्म की तारीख",
    Orgnization_Type="संगठन प्रकार",
    Preferd_Language="पसंदीदा भाषा",
    Country="देश",
    State="राज्य",
    District="जिला",
    Mobile_No="मोबाइल नंबर",
    Save="जमा करें",
    Cancel="रद्द करना",
    overview="परिवार नियोजन अवलोकन",
    Faq="अक्सर पूछे जाने वाले प्रश्न",
    keyMessage="मूल संदेश",
    counselling="परामर्श",
    Quiz="प्रश्नोत्तरी",
    library="पुस्तकालय",
    incentive=" योजना",
    AskUs="हमसे पूछें",
    Methods="गर्भनिरोधक साधन",
    submit="सुरक्षित करे",
    question_PlaceHolder="अपना प्रश्न यहाँ लिखें...",
    questionError="कृपया अपना प्रश्न दर्ज करें",
    noDataFound="कोई जानकारी उपलब्ध नहीं है",
    correct="सही",
    incorrect="ग़लत",
    response="सही उत्तर है:-",
    incentiveLabel="प्रोत्साहन",
    indeminityLabel ="क्षतिपूर्ति",
    levelText = "स्तर ",
    playQuiz= "क्या आप फिर से खेलना चाहते हैं?",
    quizAlert="कृपया पहले प्रश्नोत्तरी के दोनों स्तरों को पूरा करें।",
    quizMessage="कृपया 48 घंटे बाद पुन: प्रयास करें।"

  }

  enum language_marathi {
    downloadMsg="सामग्री यशस्वीरित्या डाउनलोड केली.",
    updateMsg="सुरू ठेवण्यासाठी टॅप करा",
    interNetMsg="कृपया तुमची इंटरनेट कनेक्टिव्हिटी तपासा.",
    noUpdate="अद्यतन उपलब्ध नाही.",
    Create_Your_Profile="आपले प्रोफाइल तयार करा",
    Tap_to_here_to_create_your_profile="आपले प्रोफाइल तयार करण्यासाठी येथे टॅप करा",
    User_Profile="वापरकर्ता प्रोफाइल",
    User_Name="नाव",
    User_Type="वापरकर्ता प्रकार",
    Gender="लिंग",
    Date_of_Birth="जन्मतारीख",
    Orgnization_Type="संघटनेचा प्रकार",
    Preferd_Language="प्राधान्यीकृत भाषा",
    Country="देश",
    State="राज्य",
    District="जिल्हा",
    Mobile_No="मोबाइल नंबर",
    Save="सेव्ह",
    Cancel="रद्द करा",
    overview="एफपी अवलोकन",
    Faq="FAQ",
    keyMessage="मुख्य संदेश",
    counselling="कन्सलिंग",
    Quiz="क्विझ",
    library="लाइब्ररी",
    incentive="स्कीम",
    AskUs="ASK यूएस",
    Methods="कॉन्ट्रॅक्सेप्टिव्ह मेथिड्स",
    submit="सबमिट करा",
    question_PlaceHolder="येथे आपला अभिप्राय / क्वेरी लिहा ...",
    questionError="कृपया आपला प्रश्न प्रविष्ट करा",
    noDataFound="डेटा उपलब्ध नाही.",
    correct="बरोबर",
    incorrect="चुकीचे",
    response="बरोबर प्रतिसाद हा आहे: -",
    incentiveLabel="प्रोत्साहन ",
    indeminityLabel ="निर्लज्जता ",
    levelText = "लेव्हल ",
    playQuiz= "आपल्याला पुन्हा खेळायचे आहे का?",
    quizAlert="कृपया प्रथम क्विझची दोन्ही पातळी पूर्ण करा.",
    quizMessage="कृपया 48 तासांनंतर पुन्हा प्रयत्न करा."
   }

  export class AppEnum {
    public Entitylanguage : typeof language = language;
    public Entity_language_english : typeof language_english = language_english;
    public Entity_language_hindi : typeof language_hindi = language_hindi;
    public Entity_language_marathi : typeof language_marathi = language_marathi;
  }



